# Generated by Django 6.0 on 2025-12-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joyeria', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
